### ISSUE TITLE
How to use generate cpp code in 3rd build system

### ISSUE THREAD

**Issue by pperehozhih** [HaxeFoundation/hxcpp#585]
Hello.

I use generated from haxe cpp files (Haxe Compiler 3.4.0, hxcpp-3.4.49)  in cmake build system (with flags from original build system). And use generated cpp file in business logic module from my project. All work with module processed in main thread. GC inits in main function.

```
int main(int argc,char** argv) {

#if defined HAXE_ENABLED
    HX_TOP_OF_STACK
    hx::Boot();
    __boot_all();
#endif // HAXE_ENABLED
```

And create necessary classes in proxy with selected StackContext

```
    hx::StackContext *_hx_ctx = hx::gMultiThreadMode ? hx::tlsStackContext : hx::gMainThreadContext;
    m_battle_manager =  ::src::SharedTestBattleManager_obj::__alloc( _hx_ctx );
```

I have got a problem with undefined behavior in this module. Any variable corrupts after some time work. (Lua target don't have this problem)

Either I use it uncorrect or add not all necessary flags.

```
-DTARGET_OS_IPHONE
-DIPHONE
-DHXCPP_M64
-D_CRT_SECURE_NO_DEPRECATE
-DHX_UNDEFINE_H
-DHAXE_ENABLED
-DHXCPP_CHECK_POINTER
-DHXCPP_STACK_LINE
-DHXCPP_STACK_TRACE
-DHXCPP_VISIT_ALLOCS
-DHXCPP_API_LEVEL=331
```

Do I use generated cpp files correctly?

**Comment by hughsando** [comment]
It can depend on where in the call stack you initialize the main function. The default behaviour does it first thing in the main routine, when means any calls to hxcpp will be "under" this call.  So if you were to attach a debugger in the hxcpp code, and trace the callstack back, you would see this HX_TOP_OF_STACK calls.
If you are attaching in your main (like shown),  this is should be ok.  If not, you will need to re-attach the top of the stack every time you call from native -> hxcpp.
If you are storing the value (eg m_battle_manager) in a native member variable, rather than on the stack (local variable), hxcpp will not be able to see this when it scans the stack.  The solution here is to use a GC root - usually via "AutoGCRoot". (hx/CFFI.h)

**Comment by pperehozhih** [comment]
Does hxcpp use custom stack unwind mechanism or swapcontext?
I run application with clang address sanitizer flag and have this error

```
AddressSanitizer: stack-buffer-underflow on address 0x7fff5fbf6160 at pc 0x00010138ca73 bp 0x7fff5fbf4fd0 sp 0x7fff5fbf4fc8
READ of size 8 at 0x7fff5fbf6160 thread T0
    #0 0x10138ca72 in hx::MarkConservative(int*, int*, hx::MarkContext*) Immix.cpp:4099
    #1 0x1013b4a27 in LocalAllocator::Mark(hx::MarkContext*) Immix.cpp:4562
    #2 0x1013b3c8c in MarkLocalAlloc(LocalAllocator*, hx::MarkContext*) Immix.cpp:4643
    #3 0x1013b2e16 in GlobalAllocator::MarkAll() Immix.cpp:3541
    #4 0x101390789 in GlobalAllocator::Collect(bool, bool, bool) Immix.cpp:3638
    #5 0x1013aeec2 in GlobalAllocator::GetFreeBlock(int, hx::ImmixAllocator*) Immix.cpp:2812
    #6 0x1013ad387 in LocalAllocator::CallAlloc(int, unsigned int) Immix.cpp:4509
    #7 0x10139b400 in hx::ImmixAllocator::alloc(hx::ImmixAllocator*, unsigned long, bool, char const*) GC.h:388
<cuted>
    #68 0x7fff9a1375ac in start (libdyld.dylib+0x35ac)

Address 0x7fff5fbf6160 is located in stack of thread T0 at offset 0 in frame
    #0 0x1013aeabf in GlobalAllocator::GetFreeBlock(int, hx::ImmixAllocator*) Immix.cpp:2792

  This frame has 2 object(s):
    [32, 36) 'dummy'
    [48, 49) 'forceCompact'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow Immix.cpp:4099 in hx::MarkConservative(int*, int*, hx::MarkContext*)

Shadow bytes around the buggy address:
  0x1fffebf7ebd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffebf7ebe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffebf7ebf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffebf7ec00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffebf7ec10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x1fffebf7ec20: 00 00 00 00 00 00 00 00 00 00 00 00[f1]f1 f1 f1
  0x1fffebf7ec30: 04 f2 01 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffebf7ec40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffebf7ec50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffebf7ec60: 00 00 00 00 f1 f1 f1 f1 01 f2 04 f2 04 f3 f3 f3
  0x1fffebf7ec70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb

```

**Comment by hughsando** [comment]
Yes - the conservative marking records the stack depth in one frame an exits that frame, but still examines the memory up to the recorded depth later.  I would call this a false positive because the values found are double-checked to ensure they are still valid.
