### ISSUE TITLE
SIGSEGV in neko_val_id () while running a simple haxe.Http.request example

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/hxcpp#644]
Hello, I encountered the following crash:

```
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff69b2aff in neko_val_id () from /opt/neko/libneko.so
Missing separate debuginfos, use: debuginfo-install gc-7.2d-7.el7.x86_64 
  glibc-2.17-106.el7_2.8.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64
(gdb) bt
#0  0x00007ffff69b2aff in neko_val_id () from /opt/neko/libneko.so
#1  0x00007ffff6bc28e0 in std_main () from /opt/neko/std.ndll
#2  0x0000000000491f95 in __hxcpp_get_proc_address (inLib=..., full_name=..., 
  inNdllProc=true, inQuietFail=false) 
  at /home/ovidiu/haxelib/hxcpp/3,4,188/src/hx/Lib.cpp:669
#3  0x0000000000492588 in __loadprim (inLib=..., inPrim=..., inArgCount=0) 
  at /home/ovidiu/haxelib/hxcpp/3,4,188/src/hx/Lib.cpp:740
#4  0x000000000044a578 in cpp::Lib_obj::load (lib=..., prim=..., nargs=0) 
  at ./src/cpp/Lib.cpp:32
#5  0x000000000041fba9 in sys::net::Host_obj::__init__ () at ./src/sys/net/Host.cpp:46
#6  0x000000000044ae30 in __boot_all () at ./src/__boot__.cpp:107
#7  0x000000000044af34 in main (argc=1, argv=0x7fffffffdeb8) 
  at /home/ovidiu/haxelib/hxcpp/3,4,188/include/hx/HxcppMain.h:92
```
It happens when I try to run the following example:

```haxe
var http: Http = new Http(url);
http.onData = function (data: String) {};
http.request();
```
It looks like it is a loading error, but it appears that is generated because of depdencies of `http.request()`. If I remove that line, the loading problem disappears.

**Comment by ovidiugabriel** [comment]
I managed to reproduce this only on Linux hxcpp version 3,4,188

**Comment by hughsando** [comment]
What haxe version are you using?  I think there is a bug with linux and
recent hxcpp and old haxe where it is still trying to use dlls somehow.
Basically, hxcpp should not be loading any dlls - here is seems to have
accidentally found a neko dll, loaded it, and crashed.
setting the environment variable HXCPP_LOAD_DEBUG should provide more
insight here.

**Comment by ovidiugabriel** [comment]
It is Haxe Compiler 3.2.0

```
No local .haxelib
HAXELIB_PATH env:(null)
HAXEPATH home:/home/ovidiu/haxelib
HAXEPATH dir:/home/ovidiu/haxelib
Read dev location from file :/home/ovidiu/haxelib/hxcpp/.dev, got (null)
Searching for std...
 try ./std.dso...
Error loading library: (./std.dso) ./std.dso: cannot open shared object file: No such file or directory
 try std.dso...
Error loading library: (std.dso) std.dso: cannot open shared object file: No such file or directory
 try /home/ovidiu/haxelib/hxcpp/3,4,188//bin/Linux64/std.dso...
Error loading library: (/home/ovidiu/haxelib/hxcpp/3,4,188//bin/Linux64/std.dso) /home/ovidiu/haxelib/hxcpp/3,4,188//bin/Linux64/std.dso: cannot open shared object file: No such file or directory
No local .haxelib
HAXELIB_PATH env:(null)
HAXEPATH home:/home/ovidiu/haxelib
HAXEPATH dir:/home/ovidiu/haxelib
Read dev location from file :/home/ovidiu/haxelib/std/.dev, got (null)
 try ./std.ndll...
Error loading library: (./std.ndll) ./std.ndll: cannot open shared object file: No such file or directory
 try std.ndll...
Loaded : std.ndll.
Found std.ndll
Segmentation fault (core dumped)

```

**Comment by ovidiugabriel** [comment]
It is Haxe Compiler 3.2.0 

```
No local .haxelib
HAXELIB_PATH env:(null)
HAXEPATH home:/home/ovidiu/haxelib
HAXEPATH dir:/home/ovidiu/haxelib
Read dev location from file :/home/ovidiu/haxelib/hxcpp/.dev, got (null)
Searching for std...
 try ./std.dso...
Error loading library: (./std.dso) ./std.dso: cannot open shared object file: No such file or directory
 try std.dso...
Error loading library: (std.dso) std.dso: cannot open shared object file: No such file or directory
 try /home/ovidiu/haxelib/hxcpp/3,4,188//bin/Linux64/std.dso...
Error loading library: (/home/ovidiu/haxelib/hxcpp/3,4,188//bin/Linux64/std.dso) /home/ovidiu/haxelib/hxcpp/3,4,188//bin/Linux64/std.dso: cannot open shared object file: No such file or directory
No local .haxelib
HAXELIB_PATH env:(null)
HAXEPATH home:/home/ovidiu/haxelib
HAXEPATH dir:/home/ovidiu/haxelib
Read dev location from file :/home/ovidiu/haxelib/std/.dev, got (null)
 try ./std.ndll...
Error loading library: (./std.ndll) ./std.ndll: cannot open shared object file: No such file or directory
 try std.ndll...
Loaded : std.ndll.
Found std.ndll
Segmentation fault (core dumped)
```

**Comment by ovidiugabriel** [comment]
It's the same with Haxe Compiler 3.4.4, NekoVM 2.1.0, hxcpp/3,4,188

**Comment by hughsando** [comment]
I have reports of this bug in 3.2 + linux in a different form.
3.4 should not have this issue though - maybe it needs a clean recompile
somehow.  Or, perhaps you are using a thirdparty lib that is using std.dll
for some reason.

**Comment by ovidiugabriel** [comment]
Yes, it looks like troubles were caused by hxssl 3.0.0-alpha. Fortunately HTTPS client code moved to haxe standard library meanwhile. Thanks!
